### ISSUE TITLE
图文素材功能没有？

### ISSUE THREAD

**Issue by ljmready** [tianyong90/willchat#15]
我看数据库有相关的表，但后台没这个功能，自动回复也无法做多图文。
另外
Middleware/account.php
 64         if ($accountUserId !== auth()->user()->id) {                                                                                                              
 65             return false;                                                                                                                                        
 66         }    
这里用!==会导致进不去管理页面，两个id的类型是不同的

**Comment by tianyong90** [comment]
@ljmready 感谢！我去检查下。很多功能是在计划内的。不过还没做完。前段时间工作忙搁置了段时间。近期会继续更新。非常欢迎PR。

**Comment by ljmready** [comment]
感谢回复。我想请教一下，微信素材这个功能，能否本地不做编辑，只在微信官网编辑，然后从微信官网同步到本地。这样关键字或自定义菜单触发时从本地数据库获取内容并发送。

**Comment by tianyong90** [comment]
@ljmready 可以啊。能通过接口完成的功能在微信公众平台上基本都有对应的操作页面。可以去看一下官方的文档并自己登录公众平台上看看。事实上素材管理公众平台上原生的做得很好了，通过接口实现会比较繁琐。
